# KISS Signal CLI Configuration
# Configuration for the Keep-It-Simple Signal Generation system

# Path to universe file containing stock symbols
universe_path: "data/nifty_large_mid.csv"

# Years of historical data to use for backtesting
historical_data_years: 3

# Directory for data caching
cache_dir: "data"

# Default hold period for positions (in trading days)
hold_period: 20

# Minimum number of trades required for a strategy to be considered valid
min_trades_threshold: 5

# Weights for calculating edge score (must sum to 1.0)
edge_score_weights:
  win_pct: 0.6    # Weight for win percentage
  sharpe: 0.4     # Weight for Sharpe ratio

# Path to the SQLite database file
database_path: "data/kiss_signal.db"

# Reporting configuration
reports_output_dir: "reports/"
edge_score_threshold: 0.50

# Strategy seeker configuration (for adaptive rule combination testing)
seeker_min_edge_score: 0.60
seeker_min_trades: 20

# Walk-forward analysis configuration (professional out-of-sample validation)
walk_forward:
  enabled: true               # DEFAULT: Professional out-of-sample validation  
  training_period: "365d"     # 1 year of training data (reduced from 2 years)
  testing_period: "90d"       # 3 months of out-of-sample testing (reduced from 6 months)
  step_size: "90d"           # Roll forward every 3 months
  min_trades_per_period: 5    # Skip periods with insufficient signals (reduced from 10)
