[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "meqsap"
version = "0.1.0"
description = "Market Equity Quantitative Strategy Analysis Platform"
readme = "README.md"
authors = [
    {name = "MEQSAP Team"}
]
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.dependencies]
pydantic = ">=2.0.0"
pyyaml = ">=6.0"
typer = ">=0.9.0"

[project.dev-dependencies]
pytest = ">=7.3.1"

[project.urls]
"Homepage" = "https://github.com/user/meqsap"
"Bug Tracker" = "https://github.com/user/meqsap/issues"

[project.scripts]
meqsap = "meqsap.cli:app"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
cache_dir = "/tmp/pytest_cache"
