# =============================================================================
# KISS Signal - Master Rules Configuration
#
# This file contains definitions for ALL implemented indicators, grouped into
# logical strategies.
#
# HOW TO USE:
# To test a strategy, make sure ONLY ONE 'baseline' and its corresponding
# 'layers' section are uncommented. The file is pre-configured to test
# Strategy 1 by default.
# =============================================================================

# -----------------------------------------------------------------------------
# STRATEGY 1: Candlestick Reversal Strategy (Recommended for Candlestick Testing)
# GOAL: Find a strong reversal pattern and confirm it's happening in favorable conditions.
# This is the CORRECT way to test candlestick patterns.
# -----------------------------------------------------------------------------
baseline:
  name: "bullish_engulfing_reversal"
  type: "engulfing_pattern"
  description: "Baseline: Enter on a bullish engulfing pattern, a strong 2-day reversal signal."
  params:
    min_body_ratio: 1.5

layers:
  - name: "filter_with_rsi_oversold"
    type: "rsi_oversold"
    description: "Filter: Ensure momentum is healthy (RSI > 40) or just recovering from oversold (crossing 30)."
    params:
      period: 14
      oversold_threshold: 30.0

  - name: "filter_with_volume_spike"
    type: "volume_spike"
    description: "Filter: Confirm the reversal is backed by a significant volume increase."
    params:
      period: 20
      spike_multiplier: 2.0 # Require volume to be at least 2x the 20-day average for higher conviction.
      price_change_threshold: 0.01

  - name: "filter_with_uptrend_context"
    type: "price_above_sma"
    description: "Filter: Ensure the reversal is happening in a broader uptrend (Price > 50-day SMA)."
    params:
      period: 50


# -----------------------------------------------------------------------------
# STRATEGY 2: Trend-Following Momentum Strategy
# GOAL: Enter a stock that is already in a confirmed uptrend.
# To use this, comment out Strategy 1 and uncomment this section.
# -----------------------------------------------------------------------------
# baseline:
#   name: "sma_10_20_crossover"
#   type: "sma_crossover"
#   description: "Baseline: Enter when the 10-day SMA crosses above the 20-day SMA."
#   params:
#     fast_period: 10
#     slow_period: 20
#
# layers:
#   - name: "confirm_with_ema_crossover"
#     type: "ema_crossover"
#     description: "Layer: Confirm with a nearly simultaneous 12/26 EMA crossover."
#     params:
#       fast_period: 12
#       slow_period: 26
#
#   - name: "confirm_with_macd_momentum"
#     type: "macd_crossover"
#     description: "Layer: Confirm that MACD is also showing bullish momentum."
#     params:
#       fast_period: 12
#       slow_period: 26
#       signal_period: 9


# -----------------------------------------------------------------------------
# STRATEGY 3: Volatility Breakout Strategy
# GOAL: Enter when a stock breaks out of a low-volatility period.
# To use this, comment out other strategies and uncomment this section.
# -----------------------------------------------------------------------------
# baseline:
#   name: "bollinger_breakout"
#   type: "bollinger_squeeze"
#   description: "Baseline: Enter on a price breakout after a Bollinger Band squeeze."
#   params:
#     period: 20
#     std_dev: 2.0
#     squeeze_threshold: 0.1
#
# layers:
#   - name: "confirm_with_breakout_volume"
#     type: "volume_spike"
#     description: "Layer: Confirm the breakout occurred on high volume."
#     params:
#       period: 20
#       spike_multiplier: 2.0
#       price_change_threshold: 0.01
#
#   - name: "confirm_with_macd_turn"
#     type: "macd_crossover"
#     description: "Layer: Confirm momentum is turning positive with the breakout."
#     params:
#       fast_period: 12
#       slow_period: 26
#       signal_period: 9


# =============================================================================
# Rule Validation Constraints (for reference)
# =============================================================================
validation:
  sma_crossover:
    fast_period: {min: 2, max: 50}
    slow_period: {min: 5, max: 200}
  rsi_oversold:
    period: {min: 2, max: 50}
    oversold_threshold: {min: 10, max: 40}
  ema_crossover:
    fast_period: {min: 2, max: 50}
    slow_period: {min: 5, max: 200}
  volume_spike:
    period: {min: 5, max: 50}
    spike_multiplier: {min: 1.5, max: 5.0}
    price_change_threshold: {min: 0.005, max: 0.05}
  hammer_pattern:
    body_ratio: {min: 0.1, max: 0.5}
    shadow_ratio: {min: 1.5, max: 3.0}
  engulfing_pattern:
    min_body_ratio: {min: 1.1, max: 2.0}
  macd_crossover:
    fast_period: {min: 5, max: 20}
    slow_period: {min: 15, max: 50}
    signal_period: {min: 5, max: 15}
  bollinger_squeeze:
    period: {min: 10, max: 50}
    std_dev: {min: 1.0, max: 3.0}
    squeeze_threshold: {min: 0.05, max: 0.2}