# Trading Rules Configuration
# 
# This file defines the technical analysis rules used for signal generation,
# structured as a baseline rule and optional layers to test on top of it.

baseline:
  name: "sma_10_20_crossover"
  type: "sma_crossover"
  description: "Baseline: Buy when 10-day SMA crosses above 20-day SMA"
  params:
    fast_period: 10
    slow_period: 20

layers:
  - name: "rsi_momentum"
    type: "rsi_oversold"
    description: "Layer: Confirm with RSI momentum (RSI > 40 or recovering from oversold)"
    params:
      period: 14
      oversold_threshold: 30.0
  - name: "ema_confirm"
    type: "ema_crossover"
    description: "Layer: Confirm with 12-day EMA crossing above 26-day EMA"
    params:
      fast_period: 12
      slow_period: 26

# Rule validation constraints (for reference)
validation:
  sma_crossover:
    fast_period: {min: 2, max: 50}
    slow_period: {min: 5, max: 200}
  rsi_oversold:
    period: {min: 2, max: 50}
    oversold_threshold: {min: 10, max: 40}
  ema_crossover:
    fast_period: {min: 2, max: 50}
    slow_period: {min: 5, max: 200}

