# =============================================================================
# SIMPLE SMA CROSSOVER BASELINE
# 
# Purpose: Generate reliable baseline performance data for trailing stop comparison
# Uses the simplest possible strategy that we know generates trades
# =============================================================================

# -----------------------------------------------------------------------------
# PRECONDITIONS: None - remove all barriers
# -----------------------------------------------------------------------------
preconditions: []

# -----------------------------------------------------------------------------
# CONTEXT FILTERS: None - remove all filters to maximize trade generation
# -----------------------------------------------------------------------------
context_filters: []

# -----------------------------------------------------------------------------
# ENTRY SIGNALS: Simple SMA crossover only
# -----------------------------------------------------------------------------
entry_signals:
  - name: "simple_sma_crossover"
    type: "sma_crossover"
    description: "Entry: Simple 10/20 SMA crossover"
    params:
      fast_period: 10
      slow_period: 20

# -----------------------------------------------------------------------------
# EXIT CONDITIONS: BASELINE - Fixed take-profit for comparison
# -----------------------------------------------------------------------------
exit_conditions:
  # --- BASELINE: Fixed Take-Profit ---
  - name: "atr_take_profit_3x"
    type: "take_profit_atr"
    description: "BASELINE: Fixed take-profit at 3x ATR"
    params:
      period: 14
      multiplier: 3.0
