# =============================================================================
# PROPOSED STRATEGY: High-Conviction Pullback in a Bull Market
#
# THESIS: Buy a strong bullish reversal pattern during a short-term pullback,
# but only when the broader market and stock trend are bullish and stable.
# Every rule here serves to confirm this single, clear thesis.
# =============================================================================

# -----------------------------------------------------------------------------
# CONTEXT FILTERS: Is the overall market environment favorable for long trades?
# We check this first to avoid wasting time on analysis during bear markets.
# -----------------------------------------------------------------------------
context_filters:
  - name: "filter_market_is_bullish"
    type: "market_above_sma"
    description: "Context 1: Don't fight the tape. The NIFTY 50 index must be above its 50-day SMA."
    params:
      index_symbol: "^NSEI"
      period: 50

# -----------------------------------------------------------------------------
# BASELINE SIGNAL: What is the core entry pattern?
# -----------------------------------------------------------------------------
baseline:
  name: "strong_bullish_engulfing"
  type: "engulfing_pattern"
  description: "Baseline: Enter on a STRONG bullish engulfing pattern. No weak signals."
  params:
    min_body_ratio: 1.5  # TIGHTENED from 1.2. We only want powerful reversals.

# -----------------------------------------------------------------------------
# LAYERS: What evidence confirms this is a high-probability setup?
# -----------------------------------------------------------------------------
layers:
  - name: "confirm_with_rsi_recovering"
    type: "rsi_oversold"
    description: "Confirmation 1: Ensure momentum is recovering from a dip (RSI crossing above 40)."
    params:
      period: 14
      oversold_threshold: 40.0 # MODIFIED: We want recovery, not deep oversold conditions.

  - name: "confirm_with_strong_volume"
    type: "volume_spike"
    description: "Confirmation 2: The reversal must be backed by significant volume (2x average)."
    params:
      period: 20
      spike_multiplier: 2.0  # TIGHTENED from 1.5. We need real conviction.
      price_change_threshold: 0.01

  - name: "confirm_with_medium_term_uptrend"
    type: "price_above_sma"
    description: "Confirmation 3: The stock itself must be in a medium-term uptrend (Price > 50-day SMA)."
    params:
      period: 50  # MODIFIED from 20. Aligns with a more robust trend.

# -----------------------------------------------------------------------------
# SELL CONDITIONS: How do we manage the trade and protect capital?
# -----------------------------------------------------------------------------
sell_conditions:
  # --- Primary Risk Management ---
  - name: "atr_stop_loss_2x"
    type: "stop_loss_atr"
    description: "RISK 1 (Catastrophic Stop): Exit if price drops 2x ATR. This is our disaster stop."
    params:
      period: 14
      multiplier: 2.0

  # --- Pattern Failure Exit ---
  # NEW: This is a crucial addition. If the reversal fails, we get out fast.
  # This assumes a rule `price_below_pattern_low` exists. If not, this is a concept to implement.
  # - name: "pattern_failed_exit"
  #   type: "price_below_pattern_low"
  #   description: "RISK 2 (Pattern Failure): Exit if price closes below the low of the engulfing pattern."
  #   params:
  #     lookback: 2 # For a 2-candle pattern

  # --- Trend Failure Exit ---
  - name: "trend_reversal_exit"
    type: "sma_cross_under"
    description: "RISK 3 (Trend Failure): Exit if the short-term trend breaks (10d SMA < 20d SMA)."
    params:
      fast_period: 10
      slow_period: 20

  # --- Profit Target ---
  - name: "atr_take_profit_4x"
    type: "take_profit_atr"
    description: "PROFIT TARGET: Exit if price rises 4x ATR, ensuring a 2:1 Reward/Risk ratio."
    params:
      period: 14
      multiplier: 4.0